### ISSUE TITLE
Missing geo.latitude produces errors

### ISSUE THREAD

**Issue by bigfootDK** [ffnord/ffmap-backend#58]
If a FF-node hat only longtitude but no latitude geo-location. The code fails with this error:
Traceback (most recent call last):
  File "/home/fabian/ffmap-backend/backend.py", line 169, in <module>
    main(options)
  File "/home/fabian/ffmap-backend/backend.py", line 134, in main
    json.dump(export_nodelist(now, nodedb), f)
  File "/home/fabian/ffmap-backend/lib/nodelist.py", line 10, in export_nodelist
    node_out["position"] = {"lat": node["nodeinfo"]["location"]["latitude"],
KeyError: 'latitude'

The result is no data in nodelist.json and wrong data in nodes.json. The meshviewer-frontend show error instead of a map.

**Comment by bigfootDK** [comment]
My fault - already fixed i current code.
